"""add_nonce_created_at_to_users

Revision ID: 851f84649df9
Revises: e387872f30a0
Create Date: 2026-02-25 14:05:46.019594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851f84649df9'
down_revision: Union[str, None] = 'e387872f30a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nonce_created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nonce_created_at')
    # ### end Alembic commands ###
