"""metamask_and_deposits

Revision ID: 98d13548e5da
Revises: c3d4e5f6a7b8
Create Date: 2026-02-25 13:25:12.745549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e2f3a4b5c6'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', name='depositstatus'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_transactions_tx_hash'), 'deposit_transactions', ['tx_hash'], unique=True)
    op.create_table('fee_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('charged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['bot_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bot_subscriptions', sa.Column('next_renewal_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bot_subscriptions', sa.Column('fee_paid_usdt', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('users', sa.Column('wallet_address', sa.String(length=42), nullable=True))
    op.add_column('users', sa.Column('nonce', sa.String(length=64), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'nonce')
    op.drop_column('users', 'wallet_address')
    op.drop_column('bot_subscriptions', 'fee_paid_usdt')
    op.drop_column('bot_subscriptions', 'next_renewal_at')
    op.drop_table('fee_income')
    op.drop_index(op.f('ix_deposit_transactions_tx_hash'), table_name='deposit_transactions')
    op.drop_table('deposit_transactions')
    # ### end Alembic commands ###
